"""
REAL Knowledge Distillation - Ollama Teacher Generates Data
=============================================================

TRUE DISTILLATION:
1. Diverse prompts → Ollama Gemma 3 270M generates responses
2. Student (BDH) learns from teacher's outputs
3. Student learns "how to think" from teacher

This is REAL distillation where teacher creates training data!
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import subprocess
import json
from pathlib import Path
import sys
import time
from datetime import datetime

sys.path.insert(0, str(Path(__file__).parent / "implementation"))

from multiscale_bdh import MultiScaleBDH, MultiScaleBDHConfig
from stable_config import get_small_model_config


# DIVERSE PROMPTS for teacher to generate training data
PROMPTS = {
    "stories": [
        "Write a short story about",
        "Once upon a time",
        "In a land far away",
        "The adventure began when",
        "Long ago, there lived",
    ],
    "science": [
        "Photosynthesis is the process by which",
        "The water cycle works because",
        "Plants need sunlight to",
        "Animals adapt to their environment by",
        "Ecosystems depend on",
    ],
    "history": [
        "The ancient Egyptians built pyramids because",
        "The Roman Empire expanded by",
        "In medieval times, people",
        "The Industrial Revolution changed",
        "World War II began when",
    ],
    "technology": [
        "Computers work by",
        "The internet connects",
        "Artificial intelligence can",
        "Machine learning algorithms",
        "Software development involves",
    ],
    "philosophy": [
        "Consciousness is defined as",
        "Ethics determines right from wrong by",
        "The meaning of life is",
        "Free will exists when",
        "Knowledge is gained through",
    ]
}


class DistillationDataset(Dataset):
    """
    Dataset generated by TEACHER (Ollama Gemma 3 270M).
    This is TRUE distillation - teacher creates training data!
    """

    def __init__(self, ollama_model="gemma3:270m", num_samples_per_prompt=50):
        print("="*70)
        print("GENERATING TRAINING DATA WITH TEACHER MODEL")
        print("="*70)
        print()
        print(f"[TEACHER] Using: {ollama_model}")
        print(f"[PROMPTS] {len(PROMPTS)} categories × {num_samples_per_prompt} samples")
        print(f"[TOTAL SAMPLES] {len(PROMPTS) * num_samples_per_prompt}")
        print()

        self.data = []
        self.generate_data(ollama_model, num_samples_per_prompt)

        print()
        print(f"[OK] Generated {len(self.data)} training samples")
        print(f"[OK] Data size: {sum(len(d['text']) for d in self.data):,} characters")
        print()

    def generate_data(self, ollama_model, num_samples_per_prompt):
        """Generate training data using Ollama teacher."""

        sample_count = 0
        total_samples = sum(len(prompts) for prompts in PROMPTS.values()) * num_samples_per_prompt

        for category, prompts in PROMPTS.items():
            print(f"[CATEGORY] {category.upper()}")
            print(f"  Prompts: {len(prompts)} × {num_samples_per_prompt} = {len(prompts) * num_samples_per_prompt} samples")

            for prompt_idx, prompt in enumerate(prompts):
                for sample_idx in range(num_samples_per_prompt):
                    # Generate completion with teacher
                    completion = self.generate_completion(ollama_model, prompt)

                    if completion:
                        # Store both prompt and completion
                        full_text = prompt + " " + completion
                        self.data.append({
                            'category': category,
                            'prompt': prompt,
                            'generated': completion,
                            'text': full_text
                        })
                        sample_count += 1

                    # Progress
                    if sample_count % 10 == 0:
                        print(f"  Generated: {sample_count}/{total_samples} ({100*sample_count/total_samples:.0f}%)")

            print(f"  [OK] {category} complete: {len([d for d in self.data if d['category'] == category])} samples")
            print()

    def generate_completion(self, model, prompt, max_tokens=200):
        """Generate text completion using Ollama."""
        try:
            result = subprocess.run(
                ["ollama", "run", model, prompt],
                capture_output=True,
                text=True,
                timeout=15
            )
            return result.stdout.strip()
        except subprocess.TimeoutExpired:
            return ""
        except Exception as e:
            print(f"[WARN] Generation failed: {e}")
            return ""

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        # Return raw text (will be converted to bytes in training loop)
        return self.data[idx]['text']


def train_epoch(student_model, dataloader, optimizer, config, device, scaler=None):
    """Train for one epoch with teacher-generated data."""

    student_model.train()
    total_loss = 0
    start_time = time.time()

    use_amp = device.type == 'cuda' and scaler is not None

    for batch_idx, text_batch in enumerate(dataloader):
        # Convert text to bytes (BDH is byte-level)
        batch_tensors = []
        for text in text_batch:
            bytes_tensor = torch.tensor(
                list(text.encode('utf-8')[:config.max_seq_len]),
                dtype=torch.long
            )
            batch_tensors.append(bytes_tensor)

        # Pad to same length
        if len(batch_tensors) > 0:
            max_len = max(t.size(0) for t in batch_tensors)
            padded_batch = []
            for t in batch_tensors:
                if t.size(0) < max_len:
                    padding = torch.zeros(max_len - t.size(0), dtype=torch.long)
                    t = torch.cat([t, padding])
                padded_batch.append(t)

            input_ids = torch.stack(padded_batch).to(device)
        else:
            continue

        # Forward pass with student
        if use_amp:
            with torch.cuda.amp.autocast():
                student_logits, _ = student_model(input_ids)

                # Next-token prediction loss
                shift_logits = student_logits[..., :-1, :].contiguous()
                shift_labels = input_ids[..., 1:].contiguous()

                loss = F.cross_entropy(
                    shift_logits.view(-1, shift_logits.size(-1)),
                    shift_labels.view(-1),
                    ignore_index=-100
                )

            optimizer.zero_grad()
            scaler.scale(loss).backward()

            scaler.unscale_(optimizer)
            if hasattr(config, 'grad_clip'):
                torch.nn.utils.clip_grad_norm_(student_model.parameters(), config.grad_clip)

            scaler.step(optimizer)
            scaler.update()
        else:
            student_logits, _ = student_model(input_ids)

            shift_logits = student_logits[..., :-1, :].contiguous()
            shift_labels = input_ids[..., 1:].contiguous()

            loss = F.cross_entropy(
                shift_logits.view(-1, shift_logits.size(-1)),
                shift_labels.view(-1),
                ignore_index=-100
            )

            optimizer.zero_grad()
            loss.backward()

            if hasattr(config, 'grad_clip'):
                torch.nn.utils.clip_grad_norm_(student_model.parameters(), config.grad_clip)

            optimizer.step()

        total_loss += loss.item()

        if (batch_idx + 1) % 10 == 0:
            elapsed = time.time() - start_time
            tokens_per_sec = (batch_idx + 1) * config.batch_size * config.max_seq_len / elapsed
            avg_loss = total_loss / (batch_idx + 1)

            if torch.cuda.is_available():
                allocated = torch.cuda.memory_allocated(0) / 1e9

            print(f"[{batch_idx+1}/{len(dataloader)}] "
                  f"loss: {avg_loss:.4f} | "
                  f"tokens/sec: {int(tokens_per_sec)} | "
                  f"GPU: {allocated:.1f}GB")

    return total_loss / len(dataloader)


def save_checkpoint(model, optimizer, config, iteration, loss, checkpoint_dir, is_best=False):
    """Save training checkpoint."""

    Path(checkpoint_dir).mkdir(parents=True, exist_ok=True)

    checkpoint = {
        'iteration': iteration,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'config': config,
        'loss': loss,
        'timestamp': datetime.now().isoformat(),
        'is_best': is_best,
        'task': 'real_distillation_ollama_gemma3_270m'
    }

    torch.save(checkpoint, Path(checkpoint_dir) / f"checkpoint_iter_{iteration}.pt")
    torch.save(checkpoint, Path(checkpoint_dir) / "checkpoint_latest.pt")

    if is_best:
        torch.save(checkpoint, Path(checkpoint_dir) / "checkpoint_best.pt")
        print(f"[BEST] New best model! Loss: {loss:.4f}")

    print(f"[OK] Checkpoint saved: iteration {iteration}, loss: {loss:.4f}")


def train(config, train_config):
    """Main training function - REAL DISTILLATION."""

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f">> Training on device: {device}")

    if torch.cuda.is_available():
        print(f"[GPU] {torch.cuda.get_device_name(0)}")
        print(f"[GPU] Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

    print()
    print("="*70)
    print("REAL KNOWLEDGE DISTILLATION")
    print("Teacher (Ollama) generates data → Student (BDH) learns")
    print("="*70)
    print()

    # Generate training data with TEACHER
    print("[PHASE 1] DATA GENERATION (Teacher creates training data)")
    print("="*70)
    train_dataset = DistillationDataset(
        ollama_model="gemma3:270m",
        num_samples_per_prompt=10  # Adjust for more/less data
    )

    # Save generated data
    data_dir = Path("teacher_data")
    data_dir.mkdir(exist_ok=True)
    data_file = data_dir / "ollama_generated_real.jsonl"

    with open(data_file, 'w', encoding='utf-8') as f:
        for item in train_dataset.data:
            f.write(json.dumps(item) + '\n')

    print(f"[OK] Saved generated data to: {data_file}")
    print()

    # Create student model
    print("[PHASE 2] STUDENT MODEL CREATION")
    print("="*70)
    student_model = MultiScaleBDH(config)
    student_model = student_model.to(device)

    try:
        student_model = torch.compile(student_model)
        print("[OK] Student compiled with torch.compile")
    except:
        print("[INFO] torch.compile not available")

    num_params = sum(p.numel() for p in student_model.parameters())
    print(f"[OK] Student created: {num_params:,} parameters")
    print(f"[COMPRESSION] Teacher: 270M → Student: ~5M ({270000000/num_params:.0f}x)")
    print()

    # A100 OPTIMIZED DataLoader
    train_loader = DataLoader(
        train_dataset,
        batch_size=train_config.batch_size,
        shuffle=True,
        num_workers=train_config.num_workers,
        pin_memory=True,
        drop_last=True,
        collate_fn=lambda x: x
    )

    print(f"[OK] Batch size: {train_config.batch_size} (A100 optimized!)")
    print(f"[OK] Workers: {train_config.num_workers}")
    print()

    # Optimizer
    optimizer = torch.optim.AdamW(
        student_model.parameters(),
        lr=train_config.learning_rate,
        weight_decay=train_config.weight_decay
    )

    # Mixed precision
    scaler = torch.cuda.amp.GradScaler() if device.type == 'cuda' else None

    # Training loop
    print("[PHASE 3] TRAINING - Student learns from teacher's data")
    print("="*70)
    print(f"   Max iterations (epochs): {train_config.max_iters}")
    print(f"   Batch size: {train_config.batch_size}")
    print(f"   Learning rate: {train_config.learning_rate}")
    print(f"   Mixed precision: {scaler is not None}")
    print(f"   Data workers: {train_config.num_workers}")
    print("="*70)
    print()

    best_val_loss = float('inf')
    t0 = time.time()

    for iteration in range(train_config.max_iters):
        epoch_start = time.time()

        # Train
        train_loss = train_epoch(
            student_model, train_loader,
            optimizer, train_config, device, scaler
        )

        epoch_time = time.time() - epoch_start

        print()
        print(f"[EPOCH {iteration+1}/{train_config.max_iters}]")
        print(f"   Loss: {train_loss:.4f}")
        print(f"   Epoch Time: {epoch_time/60:.1f} minutes")

        if torch.cuda.is_available():
            allocated = torch.cuda.memory_allocated(0) / 1e9
            total = torch.cuda.get_device_properties(0).total_memory / 1e9
            utilization = (allocated / total) * 100
            print(f"   GPU Memory: {allocated:.1f}GB / {total:.0f}GB ({utilization:.0f}%)")
        print()

        # Save checkpoint
        save_checkpoint(
            student_model, optimizer, train_config, iteration + 1, train_loss,
            train_config.checkpoint_dir, is_best=(train_loss < best_val_loss)
        )

        if train_loss < best_val_loss:
            best_val_loss = train_loss

    # Final checkpoint
    save_checkpoint(
        student_model, optimizer, train_config, train_config.max_iters, train_loss,
        train_config.checkpoint_dir, is_best=False
    )

    elapsed = time.time() - t0
    print()
    print("="*70)
    print("[DONE] REAL DISTILLATION COMPLETE!")
    print("="*70)
    print(f"[OK] Total time: {elapsed/60:.1f} minutes")
    print(f"[OK] Final loss: {train_loss:.4f}")
    print(f"[OK] Best loss: {best_val_loss:.4f}")
    print(f"[OK] Checkpoints: {train_config.checkpoint_dir}")
    print()
    print("[SUCCESS] Teacher (Ollama) created training data")
    print("[SUCCESS] Student (BDH) learned from teacher's knowledge")
    print("[SUCCESS] THIS IS TRUE DISTILLATION!")
    print("="*70)


def main():
    """Main function."""

    print("="*70)
    print("REAL KNOWLEDGE DISTILLATION")
    print("Teacher: Ollama Gemma 3 270M → Student: Multi-Scale BDH")
    print("="*70)
    print()

    # Student model configuration
    config = MultiScaleBDHConfig(
        vocab_size=256,
        n_embd=256,
        n_layer=6,
        n_head=4,
        ffn_dim=1024,
        dropout=0.1,
        max_seq_len=512,
        decay_rates=[0.95, 0.99, 0.995],
        hebbian_lr=0.001
    )

    # A100 OPTIMIZED Training configuration
    train_config = get_small_model_config()
    train_config.max_iters = 5
    train_config.batch_size = 64  # Slightly smaller due to data generation
    train_config.num_workers = 8
    train_config.checkpoint_dir = "checkpoints/bdh_real_distillation"
    train_config.resume_from = None

    print("DISTILLATION SETUP:")
    print(f"   Teacher: Ollama Gemma 3 270M (generates training data)")
    print(f"   Student: Multi-Scale BDH (~5M parameters)")
    print(f"   Compression: 54x")
    print()

    print("TRAINING DATA:")
    print(f"   Source: Teacher-generated (NOT TinyStories!)")
    print(f"   Categories: {len(PROMPTS)} (stories, science, history, etc.)")
    print(f"   Method: Teacher creates data → Student learns")
    print()

    print("A100 OPTIMIZED:")
    print(f"   Epochs: {train_config.max_iters}")
    print(f"   Batch size: {train_config.batch_size}")
    print(f"   Workers: {train_config.num_workers}")
    print()

    print("THIS IS REAL DISTILLATION:")
    print(f"   ✓ Teacher generates training data")
    print(f"   ✓ Student learns from teacher's outputs")
    print(f"   ✓ Knowledge transfer from teacher to student")
    print()

    # Start training
    train(config, train_config)


if __name__ == "__main__":
    main()
